name: pigwidgeon_backend
description: Pigwidgeon Backend Application
version: 1.0.0

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  path: ^1.8.0
  shelf: ^1.0.0
  shelf_static: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
